architecture: replication
auth:
  rootPassword: secret-root-pass
  database: my-app-db
  username: my-user
  password: my-pass

volumePermissions:
  enabled: true

secondary:
  replicaCount: 1
  persistence:
    accessModes: ["ReadWriteOnce"]
    storageClass: linode-block-storage

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring-stack

