apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-app-service-monitor
  labels:
    release: monitoring-stack
    app: java-app
spec:
  endpoints:
  - interval: 20s
    port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: java-app